### ISSUE TITLE
Empty results

### ISSUE THREAD

**Issue by asteres** [daxslab/web2py-typeahead#1]
We tried to follow the example and can tell that the data is being parsed and saved. It is being show in Local Storage but not shown in the dropdown. We are getting a dropdown of blank options.

<img width="136" alt="capture" src="https://cloud.githubusercontent.com/assets/19376283/20413376/8d8015de-ace1-11e6-8217-ba4ab5143ab0.PNG">

**Comment by cccaballero** [comment]
Thanks, @asteres, the bug was triggered when the name of the field was different to the DB field, it seems to be working fine now
